apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-chatbot.backend.fullname" . }}-secret
  labels:
    {{- include "todo-chatbot.backend.labels" . | nindent 4 }}
type: Opaque
data:
  auth-secret: {{ .Values.env.backend.AUTH_SECRET | b64enc | quote }}