{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-kafka
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-chatbot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kafka
  template:
    metadata:
      annotations:
        {{- if .Values.kafka.podAnnotations }}
        {{- toYaml .Values.kafka.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "todo-chatbot.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kafka
    spec:
      {{- with .Values.kafka.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.kafka.podSecurityContext | nindent 8 }}
      containers:
        - name: kafka
          securityContext:
            {{- toYaml .Values.kafka.securityContext | nindent 12 }}
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ include "todo-chatbot.fullname" . }}-zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://{{ include "todo-chatbot.fullname" . }}-kafka:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_NUM_PARTITIONS
              value: {{ .Values.kafka.config.num.partitions | quote }}
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: {{ .Values.kafka.config.default.replication.factor | quote }}
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: {{ .Values.kafka.config.min.insync.relicas | quote }}
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
      {{- with .Values.kafka.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafka.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafka.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}